# Use postgres/postgres user/password credentials
version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: JHipster-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jhipster
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres-data: